services:
  janus:
    image: "janus"
    # build: https://github.com/cyber-coop/janus.git
    build: .
    container_name: janus
    pull_policy: never
    environment:
      RUST_LOG: janus=info
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.toml:/config.toml
    ports:
      - "0.0.0.0:30303:30303/tcp"
      - "0.0.0.0:30303:30303/udp"

  postgres:
    image: "postgres:18"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blockchains
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # This has been changed in postgres 18
      - ./data/:/var/lib/postgresql/
